### ISSUE TITLE
Unknown Prop Warning on ResponsiveNavigation Component

### ISSUE THREAD

**Issue by zythosec** [digiaonline/react-foundation#23]
**What did you do?**
Tried to create a simple ResponsiveNavigation component.

**What did you expect to happen?**
No warning.  It looks like the isHidden prop is getting passed through to the div via the TitleBar component here: https://github.com/nordsoftware/react-foundation/blob/develop/src/components/responsive.js#L73

I would expect that either removeProps needs to be called before passing the props to the div in Titlebar or isHidden can not be passed down to TitleBar since the component does not appear to be using it: https://github.com/nordsoftware/react-foundation/blob/develop/src/components/responsive.js#L100-L110

There may be other places in the code this is happening.  I happened to stumble across this one.

**What actually happened?**
<img width="896" alt="screen shot 2016-10-03 at 10 45 15 pm" src="https://cloud.githubusercontent.com/assets/2287187/19061355/28362722-89be-11e6-9e49-ed63b9d2a2fd.png">

**What version of this module are you using?**
0.7.0
Additionally: using latest React 15.3.2 (this warning was introduced in [React 15.2.0](https://github.com/facebook/react/releases/tag/v15.2.0))

**Code**

``` jsx
render (
  <ResponsiveNavigation>
    Test
  </ResponsiveNavigation>
);
```

**Comment by kozakluke** [comment]
Any update?
Because Waring still exist in newer version of React!

**Comment by cameronb23** [comment]
Having the same issue. Documentation is also lacking, unsure of props but all I have tried have come up as unknown.

**Comment by Jalle19** [comment]
@crisu83 can you help these guys?

**Comment by kozakluke** [comment]
this project is die, I don't use this components anymore..
I suggest migrate to react-toolbox, better, nicer..

**Comment by crisu83** [comment]
This issue has been fixed.

**Comment by konradreiche** [comment]
@crisu83 How has this been fixed? I've updated my `react-foundation` dependency to `0.9.0` but the warning still persists

```
warning.js:36 Warning: Unknown prop `isHidden` on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in div (created by TitleBar)
    in TitleBar (created by ResponsiveNavigation)
    in div (created by ResponsiveNavigation)
    in ResponsiveNavigation (at index.js:29)
    in div (at index.js:28)
    in MyMenu (at index.js:98)
    in div (at index.js:73)
```

**Comment by crisu83** [comment]
My bad, I must have mixed this issue with another. I'll reopen it.

**Comment by bobwalker99** [comment]
Hi @crisu83 - your comments on [Issue 14 ](https://github.com/digiaonline/react-foundation/issues/14) imply that we shouldn't use ResponsiveNavigation and that it'll get removed - is this still the case?
